"""
Provides pynagcore module version information.
"""

# Todo.future: versions should be autogenerated.

from incremental import Version

__version__ = Version('pynagcore', 0, 1, 0)
__all__ = ["__version__"]
